repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: pretty-format-json
        args: [ --autofix ]
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
